global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'indexer-rs'

scrape_configs:
  - job_name: 'listener'
    static_configs:
      - targets: ['host.docker.internal:9091']
        labels:
          service: 'listener'

  - job_name: 'processor'
    static_configs:
      - targets: ['host.docker.internal:9092']
        labels:
          service: 'processor'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

